// <auto-generated />
namespace MvcShopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class migrationname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationname));
        
        string IMigrationMetadata.Id
        {
            get { return "201708220803198_migrationname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
